import mongoose from 'mongoose';

const quotationSchema = new mongoose.Schema(
  {
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    campaign: { type: mongoose.Schema.Types.ObjectId, ref: 'Campaign' },
    orderType: { type: String, enum: ['sample', 'bulk'], default: 'bulk' },
    quantity: { type: Number, default: 1 },
    shippingAddress: { type: mongoose.Schema.Types.Mixed, default: null },
    techPackImage: { type: String, default: '' },
    projectName: { type: String, trim: true, default: 'Untitled quotation' },
    clientName: { type: String, trim: true, default: '' },
    notes: { type: String, trim: true, default: '' },
    quoteContext: { type: mongoose.Schema.Types.Mixed, default: null },
    designSpec: { type: mongoose.Schema.Types.Mixed, required: true },
    calculation: { type: mongoose.Schema.Types.Mixed, required: true },
    versions: { type: [mongoose.Schema.Types.Mixed], default: [] },
    assignedManufacturer: { type: mongoose.Schema.Types.ObjectId, ref: 'Manufacturer', default: null },
    adminNotes: { type: String, default: '' },
    manufacturerNotes: { type: String, default: '' },
    manufacturerProposal: { type: mongoose.Schema.Types.Mixed, default: null },
    cancelledReason: { type: String, default: '' },
    cancelledBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    status: {
      type: String,
      enum: [
        'draft',
        'submitted_to_admin',
        'submitted_for_review',
        'assigned_to_manufacturer',
        'manufacturer_reviewing',
        'manufacturer_proposal_sent',
        'accepted_by_fundraiser',
        'production_started',
        'cancelled',
        'completed',
        'understanding',
        'requirements_ready',
        'configured',
        'needs_review',
        'price_calculated',
        'review',
        'final_quote',
        'approved',
        'payment_pending',
        'paid',
        'order_created',
        'manual_review',
      ],
      default: 'draft',
    },
  },
  { timestamps: true }
);

export default mongoose.model('Quotation', quotationSchema);
